name: flutter_boss_says
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  fluttertoast: ^4.0.1
  flutter_spinkit: ^4.1.2
  rxdart: ^0.22.1+4
  flutter_screenutil: ^4.0.4
  get: ^3.26.0
  flutter_easyrefresh: ^2.1.8
  date_format: ^1.0.9
  shared_preferences: '>=0.5.12+4 <2.0.0'
  json_annotation: ^3.0.1
  dio: ^3.0.1
  flutter_staggered_grid_view: ^0.3.4
  share: ^0.6.5+4
  flutter_verification_box: ^1.0.4
  flutter_slidable: ^0.5.7
  uuid: ^2.2.2
  json_serializable: ^3.5.1
  event_bus: ^1.1.1
  flutter_html: ^1.2.0
  sqflite: ^1.3.2+4
  path: ^1.7.0
  jpush_flutter: ^0.6.3
  permission_handler: ^5.1.0+2
  connectivity: ^2.0.2
  talkingdata_appanalytics_plugin:
    path: appanalytics library root
  webview_flutter: ^1.0.7
  fluwx: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    # assets-generator-begin
    # assets/img/*
    - assets/img/emptyLine.png
    - assets/img/shareDark.png
    - assets/img/weChatLogo.png
    - assets/img/favoriteDark.png
    - assets/img/bossSelect.png
    - assets/img/bossTopHead.png
    - assets/img/itemAbout.png
    - assets/img/itemContact.png
    - assets/img/settingWhite.png
    - assets/img/aboutUsLogo.png
    - assets/img/itemShare.png
    - assets/img/emptySearch.png
    - assets/img/testPhoto.png
    - assets/img/bossNormal.png
    - assets/img/itemScore.png
    - assets/img/errorIcon.png
    - assets/img/bossTopBg.png
    - assets/img/testHead.png
    - assets/img/search.png
    - assets/img/changeInfo.png
    - assets/img/favoriteAccent.png
    - assets/img/likeNormal.png
    - assets/img/bossOrderNormal.png
    - assets/img/splash.png
    - assets/img/rightGreen.png
    - assets/img/mineTopBg.png
    - assets/img/emptyBoss.png
    - assets/img/talkNormal.png
    - assets/img/mineNormal.png
    - assets/img/loginLabel.png
    - assets/img/logo.png
    - assets/img/bossSuccess.png
    - assets/img/itemClear.png
    - assets/img/itemFavorite.png
    - assets/img/bossHandLeft.png
    - assets/img/aboutUsBg.png
    - assets/img/bossLabel.png
    - assets/img/shareWhite.png
    - assets/img/contact1.png
    - assets/img/bossHandRight.png
    - assets/img/itemHistory.png
    - assets/img/contact2.png
    - assets/img/settingDark.png
    - assets/img/launchImage.png
    - assets/img/contact3.png
    - assets/img/talkSelect.png
    - assets/img/aim.png
    - assets/img/mineSelect.png
    - assets/img/likeSelect.png
    - assets/img/contact4.png
    - assets/img/testSplash.png
    - assets/img/bossOrderSelect.png
